name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '1 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Run update
        run: yarn && yarn script:update-data
        working-directory: ./scripts
        continue-on-error: true
        timeout-minutes: 45

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data
          git commit -m "Updated indexes"
          git pull --rebase
          git push